// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSRwS6wpSqondJ6ji4BCAO05-ThFV9tbw',
    appId: '1:750078014188:web:f2b4139fc8faf01746abc9',
    messagingSenderId: '750078014188',
    projectId: 'fir-crud-73703',
    authDomain: 'fir-crud-73703.firebaseapp.com',
    storageBucket: 'fir-crud-73703.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfqe5Ny6JUWbjwoueAm6ahLsDDXtD3g1A',
    appId: '1:750078014188:android:d7e8dd65f193dd8f46abc9',
    messagingSenderId: '750078014188',
    projectId: 'fir-crud-73703',
    storageBucket: 'fir-crud-73703.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9Owp25FKIGKSsDK9uBQXZp6C6hnY_Srw',
    appId: '1:750078014188:ios:a37d2c8dc787259946abc9',
    messagingSenderId: '750078014188',
    projectId: 'fir-crud-73703',
    storageBucket: 'fir-crud-73703.appspot.com',
    iosClientId: '750078014188-44sh7sl556hcq4bv2do7lajb8mjuushs.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseCrud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9Owp25FKIGKSsDK9uBQXZp6C6hnY_Srw',
    appId: '1:750078014188:ios:a37d2c8dc787259946abc9',
    messagingSenderId: '750078014188',
    projectId: 'fir-crud-73703',
    storageBucket: 'fir-crud-73703.appspot.com',
    iosClientId: '750078014188-44sh7sl556hcq4bv2do7lajb8mjuushs.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseCrud',
  );
}
